name: Build and Deploy to OVH FTP

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install LFTP
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Test FTP connection in passive mode
        env:
          FTP_USERNAME: ${{ secrets.OVH_FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.OVH_FTP_PASSWORD }}
          FTP_HOST: ftp.cluster100.hosting.ovh.net
        run: |
          lftp -d -e "set ftp:passive-mode true; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; ls" -p 21

      - name: Deploy via FTP to OVH
        if: success()
        env:
          FTP_USERNAME: ${{ secrets.OVH_FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.OVH_FTP_PASSWORD }}
          FTP_HOST: ftp.cluster100.hosting.ovh.net
          FTP_REMOTE_PATH: /www/api
        run: |
          lftp -d -e "
            set ftp:passive-mode true;
            open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
            mirror -R ./dist/ $FTP_REMOTE_PATH --delete --verbose;
            bye
          " -p 21
