- name: Test FTP connection
  env:
    FTP_USERNAME: ${{ secrets.OVH_FTP_USERNAME }}
    FTP_PASSWORD: ${{ secrets.OVH_FTP_PASSWORD }}
    FTP_HOST: ftp.cluster100.hosting.ovh.net
  run: |
    sudo apt-get update
    sudo apt-get install -y lftp
    lftp -e "set ftp:passive-mode true; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; ls; bye"
